![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [ ]:
import sys
import numpy as np

## Basic Numpy Arrays

In [ ]:
np.array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
a[0], a[1]

In [ ]:
a[0:]

In [ ]:
a[1:3]

In [ ]:
a[1:-1]

In [ ]:
a[::2]

In [ ]:
b

In [ ]:
b[0], b[2], b[-1]

In [ ]:
b[[0, 2, -1]]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [ ]:
a

In [ ]:
a.dtype

In [ ]:
b

In [ ]:
b.dtype

In [ ]:
np.array([1, 2, 3, 4], dtype=np.float64)

In [ ]:
np.array([1, 2, 3, 4], dtype=np.int8)

In [ ]:
c = np.array(['a', 'b', 'c'])

In [ ]:
c.dtype

In [ ]:
d = np.array([{'a': 1}, sys])

In [ ]:
d.dtype

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

In [ ]:
A.ndim

In [ ]:
A.size

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
B

In [ ]:
B.shape

In [ ]:
B.ndim

In [ ]:
B.size

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

In [ ]:
C.dtype

In [ ]:
C.shape

In [ ]:
C.size

In [ ]:
type(C[0])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
A[1]

In [ ]:
A[1][0]

In [ ]:
# A[d1, d2, d3, d4]

In [ ]:
A[1, 0]

In [ ]:
A[0:2]

In [ ]:
A[:, :2]

In [ ]:
A[:2, :2]

In [ ]:
A[:2, 2:]

In [ ]:
A

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

In [ ]:
A[2] = 99

In [ ]:
A

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [ ]:
a = np.array([1, 2, 3, 4])

סכם

In [ ]:
a.sum()

ממוצע

In [ ]:
a.mean()

סטיית תקן

In [ ]:
a.std()

שונות-  פיזור של המשתנים

In [ ]:
a.var()

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
A.std()

In [ ]:
A.sum(axis=0)

In [ ]:
A.sum(axis=1)

In [ ]:
A.mean(axis=0)

In [ ]:
A.mean(axis=1)

In [ ]:
A.std(axis=0)

In [ ]:
A.std(axis=1)

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a + 10

In [ ]:
a * 10

In [ ]:
a

In [ ]:
a += 100

In [ ]:
a

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
b = np.array([10, 10, 11, 10])

In [ ]:
b

In [ ]:
a + b

In [ ]:
a * b

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays - Important
_(Also called masks)_

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a[0], a[-1]

In [ ]:
a[[0, -1]]

In [ ]:
a[[True, False, False, True]]

In [ ]:
a

In [ ]:
a >= 2

In [ ]:
a[a >= 2]

In [ ]:
a.mean()

In [ ]:
a[a > a.mean()]

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A > 30

In [ ]:
A[A > 30]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

מכפלה סקלרית היא פעולה על שני וקטורים מהמרחב האוקלידי {\mathbb {R}}^{n} שמחזירה סקלר. המכפלה הסקלרית מהווה מכפלה פנימית במרחב האוקלידי.

In [ ]:
A.dot(B)

In [ ]:
A @ B

In [ ]:
B.T

In [ ]:
A

In [ ]:
B.T @ A

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

In [ ]:
np.dtype(float).itemsize

### Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

### And performance is also important

In [155]:
l = list(range(100000))

In [156]:
a = np.arange(100000)

In [157]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [158]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 21.6 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [159]:
np.random.random(size=2)

array([0.3980686 , 0.01404991])

In [160]:
np.random.normal(size=2)

array([2.15819755, 0.90149719])

In [161]:
np.random.rand(2, 4)

array([[0.24858615, 0.42534307, 0.57378044, 0.93852248],
       [0.50596096, 0.96846949, 0.2278411 , 0.23662076]])

---
### `arange`

In [162]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [164]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [165]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [166]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [167]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [168]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0, 1, 20, False)

---
### `zeros`, `ones`, `empty`

In [169]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [170]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [172]:
np.zeros((3, 3), dtype=np.int)

C:\Users\EtielYakira\AppData\Local\Temp\ipykernel_51684\383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [173]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [174]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [175]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [176]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [177]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [178]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [179]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=1)

In [181]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [180]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)